// <auto-generated />
using System;
using Gestion_dentretiens.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionEntretiens.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731115114_RefonteRolesRhEvaluateurTechnique")]
    partial class RefonteRolesRhEvaluateurTechnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeEntretien", b =>
                {
                    b.Property<int>("EntretiensId")
                        .HasColumnType("integer");

                    b.Property<int>("EvaluateursId")
                        .HasColumnType("integer");

                    b.HasKey("EntretiensId", "EvaluateursId");

                    b.HasIndex("EvaluateursId");

                    b.ToTable("EntretienEvaluateurs", (string)null);
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Creneau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DemandeEntretienId")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DemandeEntretienId");

                    b.HasIndex("EmployeId");

                    b.ToTable("Creneaux");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.DemandeEntretien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Poste")
                        .HasColumnType("text");

                    b.Property<int>("RhId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("RhId");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Entretien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreneauId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DemandeEntretienId")
                        .HasColumnType("integer");

                    b.Property<string>("LieuOuLien")
                        .HasColumnType("text");

                    b.Property<int>("Modalite")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeEntretien")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("CreneauId");

                    b.HasIndex("DemandeEntretienId");

                    b.ToTable("Entretiens");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateSaisie")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<int>("EntretienId")
                        .HasColumnType("integer");

                    b.Property<int>("Note")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("EntretienId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Personnes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Personne");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Candidat", b =>
                {
                    b.HasBaseType("Gestion_dentretiens.Models.Personne");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Employe", b =>
                {
                    b.HasBaseType("Gestion_dentretiens.Models.Personne");

                    b.Property<string>("CodeReinitialisation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpirationCode")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("text");

                    b.Property<int>("TentativesCode")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Employe");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.EvaluateurTechnique", b =>
                {
                    b.HasBaseType("Gestion_dentretiens.Models.Employe");

                    b.HasDiscriminator().HasValue("EvaluateurTechnique");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Manager", b =>
                {
                    b.HasBaseType("Gestion_dentretiens.Models.Employe");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.RH", b =>
                {
                    b.HasBaseType("Gestion_dentretiens.Models.Employe");

                    b.HasDiscriminator().HasValue("RH");
                });

            modelBuilder.Entity("EmployeEntretien", b =>
                {
                    b.HasOne("Gestion_dentretiens.Models.Entretien", null)
                        .WithMany()
                        .HasForeignKey("EntretiensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_dentretiens.Models.Employe", null)
                        .WithMany()
                        .HasForeignKey("EvaluateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Creneau", b =>
                {
                    b.HasOne("Gestion_dentretiens.Models.DemandeEntretien", "DemandeEntretien")
                        .WithMany("Creneaux")
                        .HasForeignKey("DemandeEntretienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestion_dentretiens.Models.Employe", "Employe")
                        .WithMany("Creneaux")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DemandeEntretien");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.DemandeEntretien", b =>
                {
                    b.HasOne("Gestion_dentretiens.Models.Candidat", "Candidat")
                        .WithMany("Demandes")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_dentretiens.Models.RH", "RH")
                        .WithMany("Demandes")
                        .HasForeignKey("RhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("RH");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Entretien", b =>
                {
                    b.HasOne("Gestion_dentretiens.Models.Candidat", "Candidat")
                        .WithMany("Entretiens")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_dentretiens.Models.Creneau", "Creneau")
                        .WithMany()
                        .HasForeignKey("CreneauId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestion_dentretiens.Models.DemandeEntretien", "DemandeEntretien")
                        .WithMany("Entretiens")
                        .HasForeignKey("DemandeEntretienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Creneau");

                    b.Navigation("DemandeEntretien");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Feedback", b =>
                {
                    b.HasOne("Gestion_dentretiens.Models.Employe", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_dentretiens.Models.Entretien", "Entretien")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EntretienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Entretien");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.DemandeEntretien", b =>
                {
                    b.Navigation("Creneaux");

                    b.Navigation("Entretiens");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Entretien", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Candidat", b =>
                {
                    b.Navigation("Demandes");

                    b.Navigation("Entretiens");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.Employe", b =>
                {
                    b.Navigation("Creneaux");
                });

            modelBuilder.Entity("Gestion_dentretiens.Models.RH", b =>
                {
                    b.Navigation("Demandes");
                });
#pragma warning restore 612, 618
        }
    }
}
